### ISSUE TITLE
Add default psql inside the container

### ISSUE THREAD

**Issue by NewRedsquare** [jordemort/docker-pleroma#19]
Hello,

Is this possible to add a variable to enable or not a postgresql server inside this container like `PSQL_SERVER = y` ?

**Comment by jordemort** [comment]
I didn't end up using this, and I'm only halfheartedly maintaining it, so it's unlikely that I'll put in the effort to do that.

I'd recommend just running the official Postgres container alongside this one. There is an example docker-compose.yml for doing this in the repo: https://github.com/jordemort/docker-pleroma/blob/main/example/docker-compose.yml
