### ISSUE TITLE
 Exec format error with amd64 container

### ISSUE THREAD

**Issue by NewRedsquare** [jordemort/docker-pleroma#27]
Maybe related to #26 , i get a `/opt/pleroma/releases/2.4.2/../../erts-10.7.2.16/bin/erl: 12: exec: /opt/pleroma/erts-10.7.2.16/bin/erlexec: Exec format error`

i run a x86_64 host system, i pulled the last image version

**Comment by jordemort** [comment]
Ok, I think I fixed this one in https://github.com/jordemort/docker-pleroma/pull/28 - I had a poor understanding of buildx and multi-stage builds and their interaction with GitHub Actions caching at the time I originally did this, I've cleaned it up now. The stuff on Docker Hub seems to have the correct binaries and the build should now break if it doesn't.
